### ISSUE TITLE
Detach this repository as a fork of richardotis/workshop

### ISSUE THREAD

**Issue by bocklund** [materialsgenomefoundation/workshop#8]
https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork says

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support or GitHub Premium Support. If the fork has forks of its own, let GitHub Support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

**Comment by richardotis** [comment]
Support ticket created
